# ====================================================================================================
# 作用域：
# 目前，所有设置都包含在此作用域内。
# 随着 Zensical 的发展，我们将引入更多作用域，并在适当时将设置移出 project 作用域。
# 当然，我们会提供自动重构功能，因此无需手动迁移。
# ====================================================================================================
[project]
site_name = "Air is Full"
site_description = "Air's personal website."
site_author = "Air"
site_url = "https://linxinji.github.io/personal-web/"
repo_url = "https://github.com/LinXinJi/personal-web"
repo_name = "LinXinJi/personal-web"
edit_uri = "edit/main/docs/" # 指定了编辑页面的 URI 前缀。这必须是一个相对路径，相对于 repo_url 进行解析。
site_dir = "site"            # 指定了站点将被写入的目录路径。这必须是一个相对路径，相对于配置文件进行解析。
docs_dir = "docs"            # 指定了包含源文件的目录路径。这必须是一个相对路径，相对于配置文件进行解析。
copyright = """
Copyright &copy; 2026 Air. All rights reserved.
"""
extra_css = [                # 指定了额外的 CSS 文件路径。这必须是一个相对路径，相对于 docs_dir 进行解析。
    "css/fonts.css",
    "https://unpkg.com/katex@0/dist/katex.min.css",
]
extra_javascript = [         # 指定了额外的 JavaScript 文件路径。这必须是一个相对路径，相对于 docs_dir 进行解析。
    "js/extra.js",
    "js/katex.js",
    "https://unpkg.com/katex@0/dist/katex.min.js",
    "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js",
]
nav = [
    { "首页" = "index.md" },
    { "博客" = "blog/index.md" },
    { "阅读" = [
        "books/index.md",
    ] },
    { "项目" = [
        "projects/index.md",
        { "项目1" = "projects/project1.md" }
    ] },
    { "联系" = "contact.md" },
    { "关于" = "about.md" },
]

# use_directory_urls = false   # 在构建用于离线使用时，此选项会自动设置为 false，以便您的文档无需网络服务器即可从本地文件系统浏览。默认值为 true。
# dev_addr = "localhost:8000"  # 指定了开发服务器将监听的地址和端口。默认值为 localhost:8000


# ---------------------------------------------------------------------------------------------------------
# 额外配置
# ---------------------------------------------------------------------------------------------------------
[project.extra]
homepage = "https://linxinji.github.io/personal-web/"           # 通常，页眉和侧边栏中的徽标会链接到文档的主页，该主页与 site_url 相同。可以通过以下配置更改此行为。
generator = false                                               # 页脚会显示一个由 Zensical 构建的声明，以表明网站是如何生成的。

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/LinXinJi"

[project.extra.tags]
HTML5 = "html"
JavaScript = "js"
CSS = "cs"

# -----------------------------------------------------------------------------------------------------
# 主题配置
# -----------------------------------------------------------------------------------------------------
[project.theme]
variant = "modern"                       # 现代主题 modern; 经典主题 classic
language = "zh"
# logo = "images/logo.png"                 # 网站徽标，相对于 docs_dir 进行解析。
custom_dir = "overrides"                 # 自定义目录，用于覆盖默认的主题文件。这必须是一个相对路径，相对于配置文件进行解析。
# favicon = "images/favicon.png"           # 网站图标，相对于 docs_dir 进行解析。
# font.text = "Inter"
# font.code = "JetBrains Mono"

# 主题功能
#
features = [
    "navigation.instant",                 # 即时导航：所有内部链接的点击都会被拦截并通过 XHR 调度，无需完全重新加载页面。
    "navigation.instant.prefetch",        # 即时预取：是一项新的实验性功能，当用户将鼠标悬停在链接上时，就会开始预取页面。这可以缩短用户感知的加载时间，尤其是在网络连接较慢的情况下，因为页面在导航时即可立即加载。
    "navigation.instant.progress",        # 进度指示器：为了在慢速连接下使用即时导航时提供更好的用户体验，可以启用进度指示器。
    "navigation.tracking",                # 锚点跟踪：地址栏中的 URL 将根据目录中高亮显示的活跃锚点自动更新。
    "navigation.tabs",                    # 标签页：顶部层级章节将在大于 1220px 的视口下以菜单层形式呈现在页眉下方，而在移动端保持原样显示。
    # "navigation.tabs.sticky",             # 固定标签页：在滚动时，标签页将固定在视口顶部，以提供更方便的导航。
    "navigation.sections",                # 章节：当顶级章节在大于 1220px 的视口中会以分组形式显示在侧边栏，而在移动设备上则保持原样。
    "navigation.path",                    # 导航路径：每个页面标题上方会显示面包屑导航，这有助于使用较小屏幕设备访问文档的用户更容易定位
    # "navigation.prune",                   # 导航修剪：仅可见的导航项会包含在渲染的 HTML 中， 可将构建站点的大小减少 33% 或更多。此功能标志对于拥有数千页面的文档站点尤为实用，因为导航部分占据了 HTML 的显著比重。导航剪枝功能会将所有可展开的区块替换为指向该区块首页（或区块索引页）的链接。
    "navigation.indexes",                 # 章节索引页面：文档可以直接附加到章节，这对于提供概览页面特别有用。
    "navigation.top",                     # 返回顶部：在页面顶部添加一个返回顶部按钮，以便用户可以快速访问文档的不同部分。
    "navigation.footer",                  # 页脚：在每个页面的页脚添加一个链接，指向文档上一页和下一页。
    "header.autohide",                    # 自动隐藏页眉：当用户滚动页面时，页眉会自动隐藏，以提供更多的页面空间。
    "content.tooltips",                   # 内容工具提示：当用户将鼠标悬停在文档中的元素上时，会显示一个工具提示，提供有关该元素的额外信息。
    "toc.follow",                         # 目录的锚点跟随功能：侧边栏会自动滚动，确保当前活动锚点始终可见。
    "search.highlight",                   # 搜索结果高亮：搜索结果中的匹配项将被高亮显示，以帮助用户快速识别相关内容。
    "content.action.view",                # 查看页面源代码：在每个页面的页脚添加一个查看按钮，以便用户可以查看页面的原始 HTML 代码。
    "content.action.edit",                # 编辑当前页面：在每个页面的页脚添加一个编辑按钮，以便用户可以直接在 GitHub 上编辑当前页面。
    "content.tabs.link",                  # 标签页链接：在标签页中添加链接，以便用户可以直接跳转到该标签页。
    "content.footnote.tooltips",          # 脚注工具提示：当用户将鼠标悬停在脚注引用上时，会显示一个工具提示，提供有关该脚注的额外信息。
    "content.code.select",                # 代码块选择：用户可以点击代码块来选择其中的文本，方便复制或进行其他操作。
    "content.code.copy",                  # 代码块复制：用户可以点击代码块旁边的复制按钮，将代码复制到剪贴板。
    "content.code.annotate",              # 代码块注释：用户可以在代码块中添加注释，这对于解释代码或提供上下文信息非常有用。
    "announce.dismiss",                   # 关闭公告：用户可以点击公告栏上的关闭按钮，将其隐藏起来。
]

# 浅色模式方案
#
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"  # 每个色彩方案都可以通过媒体查询与用户的浅色或深色外观系统偏好设置关联
scheme = "default"
accent = "indigo"                        # 强调色：用于标识可交互元素，例如悬停链接、按钮和滚动条。
primary = "indigo"                       # 主色调：用于文本链接，在 classic 主题中还用于页眉和侧边栏。
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# 深色模式方案
#
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
accent = "indigo"                        
primary = "indigo"                       
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"


# 图标
# 
[project.theme.icon]
# logo =                                  # 参见 Logo
# menu =                                  # 打开抽屉
# alternate =                             # 切换语言
# search =                                # 搜索图标
share = "fontawesome/solid/share"         # 分享
# close	=                                 # 重置搜索，关闭公告
# top =                                   # 返回顶部按钮
edit = "material/pencil"                  # 编辑当前页面
view = "material/eye"                     # 查看页面源代码
repo = "fontawesome/brands/git-alt"       # 仓库图标
previous = "fontawesome/solid/angle-left" # 页脚中的上一页，在移动端隐藏搜索
next = "fontawesome/solid/angle-right"    # 页脚中的下一页

# 标签图标
[project.theme.icon.tag]
default = "lucide/hash"
html = "fontawesome/brands/html5"
js = "fontawesome/brands/js"
css = "fontawesome/brands/css3"

# 提示框图标
[project.theme.icon.admonition]
note = "fontawesome/solid/note-sticky"
abstract = "fontawesome/solid/book"
info = "fontawesome/solid/circle-info"
tip = "fontawesome/solid/bullhorn"
success = "fontawesome/solid/check"
question = "fontawesome/solid/circle-question"
warning = "fontawesome/solid/triangle-exclamation"
failure = "fontawesome/solid/xmark"
danger = "fontawesome/solid/skull"
bug = "fontawesome/solid/robot"
example = "fontawesome/solid/flask"
quote = "fontawesome/solid/quote-left"


# ------------------------------------------------------------------------------------------
# Markdown 扩展
# ------------------------------------------------------------------------------------------

# 添加缩写
#
[project.markdown_extensions.abbr]

# 提示框
#
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]

# 代码块
#
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]

# 属性列表
# 允许您为 Markdown 元素添加自定义属性，这在某些情况下非常有用，例如为代码块添加行号或为图像添加自定义宽度。
#
[project.markdown_extensions.attr_list]

# 内容选项卡
#
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

# 注脚
#
[project.markdown_extensions.footnotes]

# 格式设置
#
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.tilde]

# 卡片网格
#
[project.markdown_extensions.md_in_html]

# 图表与emoji
#
[project.markdown_extensions.pymdownx.emoji]

# 图片
#
[project.markdown_extensions.pymdownx.blocks.caption]

# 列表
#
[project.markdown_extensions.def_list]
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

# 数学公式 KaTeX
#
[project.markdown_extensions.pymdownx.arithmatex]
generic = true

# mermaid 图表
#
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
    { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

# 即时预览
# 推荐使用 Zensical 内置的 Markdown 扩展来处理即时预览功能，因为它允许您为文档的每个页面或每个部分启用即时预览
#
[[project.markdown_extensions.zensical.extensions.preview.configurations]]
# sources：指触发预览的页面。当用户在这些页面上悬停或点击链接时，预览功能才会被激活。
# sources.include = [...]                   # 要启用即时预览的 Markdown 文件路径。这必须是一个相对路径，相对于 docs_dir 进行解析。
# sources.exclude = [...]                   # 要排除的 Markdown 文件路径。这必须是一个相对路径，相对于 docs_dir 进行解析。
# targets：指被预览的页面。当链接指向这些页面时，才会显示预览内容。
# targets.include = [...]                   # 要启用即时预览的 HTML 文件路径。这必须是一个相对路径，相对于 docs_dir 进行解析。
# targets.exclude = [...]                   # 要排除的 HTML 文件路径。这必须是一个相对路径，相对于 docs_dir 进行解析。